### ISSUE TITLE
Trouble in using sinusoid to run the code

### ISSUE THREAD

**Issue by im73** [tristandeleu/pytorch-maml#1]
I've installed all the dependencies in the requirements.txt, but when I used “python train.py /data --dataset sinusoid --num-epochs 1000 --output-folder /data/rst ”to run, It get trouble in the dataloader in /metalearners/maml.py line 171
    for results in self.train_iter(dataloader, max_batches=max_batches)
the final error message is 
    File "~/torchmeta_env/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 57, in to_tensor raise ValueError('pic should be 2/3 dimensional. Got {} dimensions        
ValueError: pic should be 2/3 dimensional. Got 1 dimensions.  
is that ok when you use it in sinusoid?

In addition,in train.py line 48 and 51, when it is sinusoid, the dataset_transform is still ClassSplitter.

btw the code in the model.py line 93
self.features = MetaSequential(OrderedDict([('layer{0}'.format(i + 1),
            MetaSequential(OrderedDict([
                ('linear', MetaLinear(hidden_size, layer_sizes[i + 1], bias=True)),
                ('relu', nn.ReLU())
            ])))] for (i, hidden_size) in enumerate(layer_sizes[:-1])))
should be
self.features = MetaSequential(OrderedDict([('layer{0}'.format(i + 1),
            MetaSequential(OrderedDict([
                ('linear', MetaLinear(hidden_size, layer_sizes[i + 1], bias=True)),
                ('relu', nn.ReLU())
            ]))) for (i, hidden_size) in enumerate(layer_sizes[:-1]) ] ))
you add the '[' in the wrong place

**Comment by tristandeleu** [comment]
Thank you very much! Sinusoid was indeed a dataset I didn't test.
