### ISSUE TITLE
How can I apply this code on my own dataset?

### ISSUE THREAD

**Issue by qlz58793** [tristandeleu/pytorch-maml#3]

**Comment by tristandeleu** [comment]
This implementation of MAML uses [Torchmeta](https://github.com/tristandeleu/pytorch-meta), so probably the easiest option to apply the code to your own dataset is to use the same interface as Torchmeta for your dataset. See for example how [Omniglot is implemented](https://github.com/tristandeleu/pytorch-meta/blob/master/torchmeta/datasets/omniglot.py), and how you could adapt it for your own dataset.
